/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedReviseRouteImport } from './routes/_authenticated/revise'
import { Route as AuthenticatedChapterChapterSlugRouteImport } from './routes/_authenticated/chapter.$chapterSlug'
import { Route as AuthenticatedLessonLessonIdRouteImport } from './routes/_authenticated/lesson.$lessonId'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviseRoute = AuthenticatedReviseRouteImport.update({
  id: '/revise',
  path: '/revise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChapterChapterSlugRoute =
  AuthenticatedChapterChapterSlugRouteImport.update({
    id: '/chapter/$chapterSlug',
    path: '/chapter/$chapterSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonLessonIdRoute =
  AuthenticatedLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/revise': typeof AuthenticatedReviseRoute
  '/chapter/$chapterSlug': typeof AuthenticatedChapterChapterSlugRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/revise': typeof AuthenticatedReviseRoute
  '/chapter/$chapterSlug': typeof AuthenticatedChapterChapterSlugRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/revise': typeof AuthenticatedReviseRoute
  '/_authenticated/chapter/$chapterSlug': typeof AuthenticatedChapterChapterSlugRoute
  '/_authenticated/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/learn'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/pricing'
    | '/revise'
    | '/chapter/$chapterSlug'
    | '/lesson/$lessonId'
    | '/api/public/razorpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/learn'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/pricing'
    | '/revise'
    | '/chapter/$chapterSlug'
    | '/lesson/$lessonId'
    | '/api/public/razorpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/learn'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/pricing'
    | '/_authenticated/revise'
    | '/_authenticated/chapter/$chapterSlug'
    | '/_authenticated/lesson/$lessonId'
    | '/api/public/razorpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LearnRoute: typeof LearnRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revise': {
      id: '/_authenticated/revise'
      path: '/revise'
      fullPath: '/revise'
      preLoaderRoute: typeof AuthenticatedReviseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chapter/$chapterSlug': {
      id: '/_authenticated/chapter/$chapterSlug'
      path: '/chapter/$chapterSlug'
      fullPath: '/chapter/$chapterSlug'
      preLoaderRoute: typeof AuthenticatedChapterChapterSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson/$lessonId': {
      id: '/_authenticated/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedReviseRoute: typeof AuthenticatedReviseRoute
  AuthenticatedChapterChapterSlugRoute: typeof AuthenticatedChapterChapterSlugRoute
  AuthenticatedLessonLessonIdRoute: typeof AuthenticatedLessonLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedReviseRoute: AuthenticatedReviseRoute,
  AuthenticatedChapterChapterSlugRoute: AuthenticatedChapterChapterSlugRoute,
  AuthenticatedLessonLessonIdRoute: AuthenticatedLessonLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LearnRoute: LearnRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
