
INSERT INTO public.exams (slug, name, short_name, description, sort_order) VALUES
('upsc','UPSC / State PSC','UPSC','Civil services prelims General Studies: history, polity, geography, economy, environment and current affairs.',1),
('ssc','SSC CGL / CHSL','SSC','Staff Selection Commission General Awareness: static GK, science, polity, history and current affairs.',2),
('banking','Banking (IBPS / SBI)','Banking','General Awareness with a strong banking, financial and current affairs focus.',3),
('railway','Railways (RRB NTPC / Group D)','Railways','General Awareness and General Science for RRB exams.',4);

INSERT INTO public.subjects (slug, name, icon, description, sort_order) VALUES
('indian-history','Indian History','scroll','Ancient, Medieval, Modern and Post-Independence India, section and chapter wise.',1),
('art-culture','Art & Culture','palette','Architecture, dance, music, painting, festivals and UNESCO heritage of India.',2),
('polity','Indian Polity','landmark','Constitution, institutions, rights, federalism and governance.',3),
('geography','Geography','globe','Physical, Indian and world geography with map-based facts.',4),
('economy','Indian Economy','trending-up','Basic concepts, banking, budget, planning and current economic affairs.',5),
('science-tech','Science & Technology','atom','Physics, chemistry, biology basics and applied technology for exams.',6),
('environment','Environment & Ecology','leaf','Ecosystems, biodiversity, climate change, conventions and Indian conservation.',7),
('current-affairs','Current Affairs','newspaper','Themed current affairs notes linked to the static syllabus.',8),
('static-gk','Static GK','book','Awards, sports, books, organisations, days and miscellaneous facts.',9),
('banking-awareness','Banking Awareness','banknote','RBI, monetary policy, banking products, regulators and financial abbreviations.',10);

INSERT INTO public.exam_subjects (exam_slug, subject_slug, weight) VALUES
('upsc','indian-history','High'),('upsc','art-culture','Medium'),('upsc','polity','High'),('upsc','geography','High'),('upsc','economy','High'),('upsc','science-tech','Medium'),('upsc','environment','High'),('upsc','current-affairs','High'),
('ssc','indian-history','High'),('ssc','art-culture','Low'),('ssc','polity','High'),('ssc','geography','Medium'),('ssc','economy','Medium'),('ssc','science-tech','High'),('ssc','static-gk','High'),('ssc','current-affairs','High'),
('banking','economy','High'),('banking','banking-awareness','High'),('banking','current-affairs','High'),('banking','static-gk','Medium'),('banking','polity','Low'),
('railway','indian-history','Medium'),('railway','polity','Medium'),('railway','geography','Medium'),('railway','science-tech','High'),('railway','static-gk','High'),('railway','current-affairs','Medium');

INSERT INTO public.sections (slug, subject_slug, name, description, sort_order) VALUES
('hist-ancient','indian-history','Ancient India','From prehistory and the Indus Valley to the Vardhana dynasty.',1),
('hist-medieval','indian-history','Medieval India','Early medieval kingdoms, Delhi Sultanate, Vijayanagara, Mughals and Marathas.',2),
('hist-modern','indian-history','Modern India','European arrival, colonial rule, reform movements and the freedom struggle.',3),
('hist-post','indian-history','Post-Independence India','Integration of states, wars, emergency and economic reform.',4),
('ac-architecture','art-culture','Architecture & Heritage','Temple styles, stupas, forts and UNESCO sites.',1),
('ac-performing','art-culture','Performing & Visual Arts','Classical dance, music gharanas, painting schools and theatre.',2),
('pol-constitution','polity','Constitution & Basics','Making of the Constitution, preamble, sources, schedules and amendments.',1),
('pol-institutions','polity','Institutions & Governance','Executive, legislature, judiciary, constitutional bodies and federalism.',2),
('geo-physical','geography','Physical Geography','Earth, atmosphere, landforms, oceans and climate.',1),
('geo-india','geography','Indian Geography','Relief, rivers, soils, agriculture, minerals and transport.',2),
('eco-basics','economy','Economic Basics','National income, inflation, growth, poverty and unemployment.',1),
('eco-fiscal','economy','Fiscal & External Sector','Budget, taxation, trade, balance of payments and planning.',2),
('sci-physics','science-tech','Physics & Chemistry','Motion, energy, light, sound, elements, acids and everyday chemistry.',1),
('sci-bio','science-tech','Biology & Technology','Human body, nutrition, diseases, space, defence and IT.',2),
('env-ecology','environment','Ecology & Biodiversity','Ecosystems, food chains, species, protected areas.',1),
('env-climate','environment','Climate & Conventions','Climate change, pollution, treaties and Indian environmental law.',2),
('ca-national','current-affairs','National Affairs','Schemes, policies, appointments and national developments.',1),
('ca-international','current-affairs','International Affairs','Summits, organisations, bilateral relations and global events.',2),
('sgk-awards','static-gk','Awards, Sports & Days','Honours, tournaments, important days and personalities.',1),
('sgk-orgs','static-gk','Organisations & Miscellany','Headquarters, abbreviations, books, authors and first-in-India facts.',2),
('bank-rbi','banking-awareness','RBI & Monetary Policy','Functions of RBI, policy rates, money supply and regulation.',1),
('bank-products','banking-awareness','Banking Products & Regulators','Accounts, loans, NPAs, payment systems, SEBI, IRDAI and financial inclusion.',2);

INSERT INTO public.chapters (slug, section_slug, title, summary, sort_order, is_free, est_minutes) VALUES
('hist-anc-01','hist-ancient','Prehistoric Cultures of India','Palaeolithic to Chalcolithic phases, key sites and tool traditions.',1,true,12),
('hist-anc-02','hist-ancient','Indus Valley Civilisation','Extent, town planning, economy, seals, script and decline theories.',2,true,15),
('hist-anc-03','hist-ancient','Vedic Age','Early and Later Vedic society, polity, economy and literature.',3,false,14),
('hist-anc-04','hist-ancient','Rise of Jainism and Buddhism','Causes, doctrines, councils, sects and spread.',4,false,14),
('hist-anc-05','hist-ancient','Mahajanapadas and Magadha','Sixteen mahajanapadas, Haryanka, Shishunaga and Nanda dynasties.',5,false,12),
('hist-anc-06','hist-ancient','The Mauryan Empire','Chandragupta, Ashoka, edicts, administration and decline.',6,false,16),
('hist-anc-07','hist-ancient','Post-Mauryan Kingdoms','Shungas, Satavahanas, Indo-Greeks, Kushanas and Sangam age.',7,false,14),
('hist-anc-08','hist-ancient','The Gupta Empire and After','Golden age, administration, science, Harshavardhana and Vardhanas.',8,false,15),
('hist-med-01','hist-medieval','Early Medieval Kingdoms','Rajputs, Cholas, Palas, Pratiharas and the tripartite struggle.',1,false,14),
('hist-med-02','hist-medieval','Arab and Turkish Invasions','Muhammad bin Qasim, Mahmud of Ghazni and Muhammad Ghori.',2,false,12),
('hist-med-03','hist-medieval','The Delhi Sultanate','Slave, Khalji, Tughlaq, Sayyid and Lodi dynasties.',3,false,16),
('hist-med-04','hist-medieval','Vijayanagara and Bahmani Kingdoms','Foundation, rulers, Krishnadeva Raya, Talikota and Deccan sultanates.',4,false,13),
('hist-med-05','hist-medieval','Bhakti and Sufi Movements','Saints, sects, teachings and social impact.',5,false,12),
('hist-med-06','hist-medieval','The Mughal Empire','Babur to Aurangzeb, administration, mansabdari and art.',6,false,18),
('hist-med-07','hist-medieval','Marathas and Later Mughals','Shivaji, Peshwas, Anglo-Maratha wars and Mughal decline.',7,false,14),
('hist-mod-01','hist-modern','Advent of Europeans','Portuguese, Dutch, French and English trading companies.',1,false,12),
('hist-mod-02','hist-modern','British Expansion in India','Plassey, Buxar, subsidiary alliance, doctrine of lapse and annexations.',2,false,15),
('hist-mod-03','hist-modern','Economic Impact of Colonial Rule','Drain of wealth, land revenue systems, deindustrialisation and famines.',3,false,14),
('hist-mod-04','hist-modern','Revolt of 1857','Causes, centres, leaders, suppression and consequences.',4,false,13),
('hist-mod-05','hist-modern','Socio-Religious Reform Movements','Brahmo Samaj, Arya Samaj, Aligarh, and social legislation.',5,false,13),
('hist-mod-06','hist-modern','Rise of Nationalism and the INC','Moderates, extremists, Swadeshi, Surat split and revolutionaries.',6,false,15),
('hist-mod-07','hist-modern','Gandhian Era','Champaran to Quit India, key movements, acts and pacts.',7,false,18),
('hist-mod-08','hist-modern','Towards Independence and Partition','Cripps, Cabinet Mission, Mountbatten Plan and Independence Act.',8,false,14),
('hist-post-01','hist-post','Integration of Princely States','Instrument of Accession, Hyderabad, Junagadh, Kashmir and Sardar Patel.',1,false,12),
('hist-post-02','hist-post','Reorganisation of States','Linguistic states, States Reorganisation Act and later state formation.',2,false,11),
('hist-post-03','hist-post','Wars and Foreign Policy','1962, 1965, 1971, Kargil, non-alignment and nuclear policy.',3,false,13),
('hist-post-04','hist-post','Emergency and Coalition Politics','1975 Emergency, Janata government and the coalition era.',4,false,12),
('hist-post-05','hist-post','Economic Reforms of 1991','Crisis, LPG reforms and their consequences.',5,false,11),
('ac-arch-01','ac-architecture','Ancient Indian Architecture','Harappan, Mauryan pillars, stupas, rock-cut caves.',1,true,13),
('ac-arch-02','ac-architecture','Temple Architecture Styles','Nagara, Dravida and Vesara with key examples.',2,true,13),
('ac-arch-03','ac-architecture','Indo-Islamic and Colonial Architecture','Delhi Sultanate, Mughal, provincial and colonial styles.',3,false,13),
('ac-arch-04','ac-architecture','UNESCO World Heritage Sites in India','Cultural, natural and mixed sites with locations.',4,false,12),
('ac-perf-01','ac-performing','Classical Dances of India','Eight classical forms, states, features and exponents.',1,false,12),
('ac-perf-02','ac-performing','Indian Music Traditions','Hindustani and Carnatic music, ragas, instruments and gharanas.',2,false,12),
('ac-perf-03','ac-performing','Painting Schools and Handicrafts','Mural, miniature, folk painting and GI-tagged crafts.',3,false,12),
('ac-perf-04','ac-performing','Festivals, Fairs and Theatre','Regional festivals, folk theatre and tribal traditions.',4,false,11),
('pol-con-01','pol-constitution','Making of the Constitution','Constituent Assembly, committees, sources and enactment.',1,true,13),
('pol-con-02','pol-constitution','Preamble, Union and Territory','Keywords of the Preamble, Articles 1-4 and state reorganisation.',2,true,12),
('pol-con-03','pol-constitution','Fundamental Rights','Articles 12-35, writs, exceptions and landmark cases.',3,false,16),
('pol-con-04','pol-constitution','DPSP and Fundamental Duties','Articles 36-51A, classification and conflicts with rights.',4,false,13),
('pol-con-05','pol-constitution','Amendments and Basic Structure','Article 368, important amendments and judicial doctrine.',5,false,13),
('pol-inst-01','pol-institutions','Union Executive','President, Vice-President, PM and Council of Ministers.',1,false,14),
('pol-inst-02','pol-institutions','Parliament','Composition, sessions, bills, motions and committees.',2,false,16),
('pol-inst-03','pol-institutions','Judiciary','Supreme Court, High Courts, judicial review and PIL.',3,false,14),
('pol-inst-04','pol-institutions','State Government and Local Bodies','Governor, CM, 73rd and 74th amendments and panchayati raj.',4,false,14),
('pol-inst-05','pol-institutions','Constitutional and Statutory Bodies','ECI, UPSC, CAG, Finance Commission, NHRC, CVC and Lokpal.',5,false,14),
('geo-phy-01','geo-physical','Universe, Earth and Motions','Solar system, latitudes, longitudes, time zones and seasons.',1,true,13),
('geo-phy-02','geo-physical','Interior of the Earth and Landforms','Layers, plate tectonics, earthquakes, volcanoes and rocks.',2,true,13),
('geo-phy-03','geo-physical','Atmosphere and Climate','Layers, pressure belts, winds, cyclones and climate types.',3,false,13),
('geo-phy-04','geo-physical','Oceanography','Ocean relief, currents, tides, salinity and coral reefs.',4,false,12),
('geo-ind-01','geo-india','Physiographic Divisions','Himalayas, plains, plateau, coasts and islands.',1,false,13),
('geo-ind-02','geo-india','Drainage System','Himalayan and peninsular rivers, tributaries and projects.',2,false,13),
('geo-ind-03','geo-india','Climate, Soils and Vegetation','Monsoon mechanism, soil types and forest types.',3,false,13),
('geo-ind-04','geo-india','Agriculture, Minerals and Industry','Cropping patterns, revolutions, mineral belts and industrial regions.',4,false,14),
('eco-bas-01','eco-basics','Basic Economic Concepts','Micro vs macro, sectors, GDP, GNP, NNP and deflator.',1,true,13),
('eco-bas-02','eco-basics','National Income and Growth','Measurement methods, base year, growth vs development, HDI.',2,true,12),
('eco-bas-03','eco-basics','Inflation and Money','Types, WPI, CPI, causes, control and money supply measures.',3,false,13),
('eco-bas-04','eco-basics','Poverty, Unemployment and Schemes','Estimation, types, MGNREGA and welfare schemes.',4,false,13),
('eco-fis-01','eco-fiscal','Union Budget and Taxation','Budget documents, deficits, FRBM, direct and indirect taxes, GST.',1,false,14),
('eco-fis-02','eco-fiscal','Planning and Institutions','Five year plans, NITI Aayog, Finance Commission.',2,false,12),
('eco-fis-03','eco-fiscal','External Sector','BoP, exchange rates, FDI vs FPI, trade policy and WTO.',3,false,13),
('eco-fis-04','eco-fiscal','Financial Markets','Money market, capital market, SEBI, instruments and indices.',4,false,13),
('sci-phy-01','sci-physics','Motion, Force and Energy','Laws of motion, gravitation, work, power and simple machines.',1,true,13),
('sci-phy-02','sci-physics','Heat, Light and Sound','Thermodynamics basics, reflection, refraction, lenses and waves.',2,true,13),
('sci-phy-03','sci-physics','Electricity and Magnetism','Current, Ohm law, circuits, magnets and electromagnetic induction.',3,false,12),
('sci-phy-04','sci-physics','Chemistry Essentials','Atomic structure, periodic table, acids, bases, salts and alloys.',4,false,14),
('sci-bio-01','sci-bio','Human Body Systems','Digestive, circulatory, respiratory, nervous and endocrine systems.',1,false,14),
('sci-bio-02','sci-bio','Nutrition, Diseases and Health','Vitamins, deficiency diseases, pathogens, vaccines and immunity.',2,false,13),
('sci-bio-03','sci-bio','Plant and Cell Biology','Cell organelles, photosynthesis, genetics basics and classification.',3,false,13),
('sci-bio-04','sci-bio','Space, Defence and IT','ISRO missions, launch vehicles, missiles and computer basics.',4,false,14),
('env-eco-01','env-ecology','Ecosystem and Energy Flow','Components, food chains, pyramids and biogeochemical cycles.',1,true,12),
('env-eco-02','env-ecology','Biodiversity and Species','Hotspots, IUCN categories, endemic and endangered species.',2,true,12),
('env-eco-03','env-ecology','Protected Areas of India','National parks, sanctuaries, biosphere reserves and Ramsar sites.',3,false,13),
('env-eco-04','env-ecology','Conservation Projects','Project Tiger, Project Elephant, CAMPA and wildlife corridors.',4,false,12),
('env-cli-01','env-climate','Climate Change Science','Greenhouse gases, global warming, carbon cycle and impacts.',1,false,13),
('env-cli-02','env-climate','Pollution and Waste','Air, water, soil, noise pollution, indices and waste rules.',2,false,13),
('env-cli-03','env-climate','International Conventions','UNFCCC, Kyoto, Paris, CBD, CITES, Ramsar and Montreal.',3,false,13),
('env-cli-04','env-climate','Indian Environmental Laws','EPA 1986, Forest Acts, NGT, EIA and CPCB.',4,false,12),
('ca-nat-01','ca-national','Government Schemes','Flagship central schemes, ministries and objectives.',1,true,12),
('ca-nat-02','ca-national','Policies and Reports','Recent policies, indices and national reports.',2,true,12),
('ca-nat-03','ca-national','Appointments and Obituaries','Key appointments, resignations and notable personalities.',3,false,10),
('ca-nat-04','ca-national','Defence and Internal Security','Exercises, acquisitions and security frameworks.',4,false,11),
('ca-int-01','ca-international','Summits and Conferences','G20, BRICS, SCO, QUAD, ASEAN and their outcomes.',1,false,12),
('ca-int-02','ca-international','International Organisations','UN bodies, IMF, World Bank, WHO, WTO and their heads.',2,false,12),
('ca-int-03','ca-international','India and its Neighbours','Bilateral relations, agreements and border issues.',3,false,12),
('sgk-awa-01','sgk-awards','National and International Awards','Bharat Ratna, Padma, Nobel, Oscars, Booker and Jnanpith.',1,true,11),
('sgk-awa-02','sgk-awards','Sports and Tournaments','Cups, venues, terms, Olympic facts and Indian sports.',2,true,12),
('sgk-awa-03','sgk-awards','Important Days and Themes','National and international days with themes.',3,false,10),
('sgk-org-01','sgk-orgs','Headquarters and Abbreviations','Organisations, their HQs, heads and common abbreviations.',1,false,11),
('sgk-org-02','sgk-orgs','Books, Authors and Firsts','Famous books, authors and first-in-India facts.',2,false,11),
('sgk-org-03','sgk-orgs','Dances, Festivals and Monuments of States','State-wise static GK quick facts.',3,false,11),
('bank-rbi-01','bank-rbi','RBI: Structure and Functions','Establishment, nationalisation, governors and core functions.',1,true,12),
('bank-rbi-02','bank-rbi','Monetary Policy and Rates','Repo, reverse repo, CRR, SLR, MSF, MPC and transmission.',2,true,13),
('bank-rbi-03','bank-rbi','Money Supply and Instruments','M0 to M3, OMO, LAF, market stabilisation scheme.',3,false,12),
('bank-pro-01','bank-products','Bank Accounts and Deposits','Types of accounts, KYC, DICGC and deposit products.',1,false,12),
('bank-pro-02','bank-products','Loans, Priority Sector and NPAs','Credit types, PSL targets, NPA classification and SARFAESI.',2,false,13),
('bank-pro-03','bank-products','Payment Systems and Digital Banking','NEFT, RTGS, IMPS, UPI, NPCI and cards.',3,false,12),
('bank-pro-04','bank-products','Regulators and Financial Inclusion','SEBI, IRDAI, PFRDA, Jan Dhan, mudra and microfinance.',4,false,12);

INSERT INTO public.badges (slug, name, description, icon, threshold, kind) VALUES
('first-steps','First Steps','Complete your first lesson.','footprints',1,'lessons'),
('scholar','Scholar','Complete 10 lessons.','graduation-cap',10,'lessons'),
('marathoner','Marathoner','Complete 50 lessons.','medal',50,'lessons'),
('streak-3','Warming Up','Maintain a 3-day streak.','flame',3,'streak'),
('streak-7','Week Warrior','Maintain a 7-day streak.','flame',7,'streak'),
('streak-30','Unstoppable','Maintain a 30-day streak.','flame',30,'streak'),
('xp-500','Rising Star','Earn 500 XP.','star',500,'xp'),
('xp-2000','Topper Track','Earn 2000 XP.','trophy',2000,'xp'),
('focus-10','Deep Focus','Finish 10 Pomodoro sessions.','timer',10,'focus');
